- name: install common tools on all servers (generic)
  hosts: all
  become: yes
  tasks: 
   - name: install curl
     package:
      name: curl
      state: present

   - name: install wget
     package:
      name: wget
      state: present

   - name: install tree
     package:
      name: tree
      state: present
