---
- name: Setup Apache webserver with custom configuration
  hosts: localhost
  connection: local
  become: yes

  vars:
    apache_listen_port: 8080
    apache_vhosts:
      - servername: localhost
        documentroot: /var/www/myapp
        extra_parameters: |
          <Directory "/var/www/myapp">
              AllowOverride All
          </Directory>
    apache_mods_enabled:
      - rewrite

  roles:
    - role: geerlingguy.apache
      
